export interface Country {
    code: string;
    name: string;
    dialCode: string;
    flag: string;
    phoneLength: number; // Longueur maximale du numéro (sans l'indicatif)
}

export const countries: Country[] = [
    { code: "AF", name: "Afghanistan", dialCode: "+93", flag: "🇦🇫", phoneLength: 9 },
    { code: "ZA", name: "Afrique du Sud", dialCode: "+27", flag: "🇿🇦", phoneLength: 9 },
    { code: "AL", name: "Albanie", dialCode: "+355", flag: "🇦🇱", phoneLength: 9 },
    { code: "DZ", name: "Algérie", dialCode: "+213", flag: "🇩🇿", phoneLength: 9 },
    { code: "DE", name: "Allemagne", dialCode: "+49", flag: "🇩🇪", phoneLength: 11 },
    { code: "AD", name: "Andorre", dialCode: "+376", flag: "🇦🇩", phoneLength: 6 },
    { code: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴", phoneLength: 9 },
    { code: "AI", name: "Anguilla", dialCode: "+1264", flag: "🇦🇮", phoneLength: 10 },
    { code: "AG", name: "Antigua-et-Barbuda", dialCode: "+1268", flag: "🇦🇬", phoneLength: 10 },
    { code: "SA", name: "Arabie saoudite", dialCode: "+966", flag: "🇸🇦", phoneLength: 9 },
    { code: "AR", name: "Argentine", dialCode: "+54", flag: "🇦🇷", phoneLength: 10 },
    { code: "AM", name: "Arménie", dialCode: "+374", flag: "🇦🇲", phoneLength: 8 },
    { code: "AW", name: "Aruba", dialCode: "+297", flag: "🇦🇼", phoneLength: 7 },
    { code: "AU", name: "Australie", dialCode: "+61", flag: "🇦🇺", phoneLength: 9 },
    { code: "AT", name: "Autriche", dialCode: "+43", flag: "🇦🇹", phoneLength: 10 },
    { code: "AZ", name: "Azerbaïdjan", dialCode: "+994", flag: "🇦🇿", phoneLength: 9 },
    { code: "BS", name: "Bahamas", dialCode: "+1242", flag: "🇧🇸", phoneLength: 10 },
    { code: "BH", name: "Bahreïn", dialCode: "+973", flag: "🇧🇭", phoneLength: 8 },
    { code: "BD", name: "Bangladesh", dialCode: "+880", flag: "🇧🇩", phoneLength: 10 },
    { code: "BB", name: "Barbade", dialCode: "+1246", flag: "🇧🇧", phoneLength: 10 },
    { code: "BE", name: "Belgique", dialCode: "+32", flag: "🇧🇪", phoneLength: 9 },
    { code: "BZ", name: "Belize", dialCode: "+501", flag: "🇧🇿", phoneLength: 7 },
    { code: "BJ", name: "Bénin", dialCode: "+229", flag: "🇧🇯", phoneLength: 8 },
    { code: "BM", name: "Bermudes", dialCode: "+1441", flag: "🇧🇲", phoneLength: 10 },
    { code: "BT", name: "Bhoutan", dialCode: "+975", flag: "🇧🇹", phoneLength: 8 },
    { code: "BY", name: "Biélorussie", dialCode: "+375", flag: "🇧🇾", phoneLength: 9 },
    { code: "BO", name: "Bolivie", dialCode: "+591", flag: "🇧🇴", phoneLength: 8 },
    { code: "BA", name: "Bosnie-Herzégovine", dialCode: "+387", flag: "🇧🇦", phoneLength: 8 },
    { code: "BW", name: "Botswana", dialCode: "+267", flag: "🇧🇼", phoneLength: 8 },
    { code: "BR", name: "Brésil", dialCode: "+55", flag: "🇧🇷", phoneLength: 11 },
    { code: "BN", name: "Brunei", dialCode: "+673", flag: "🇧🇳", phoneLength: 7 },
    { code: "BG", name: "Bulgarie", dialCode: "+359", flag: "🇧🇬", phoneLength: 9 },
    { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫", phoneLength: 8 },
    { code: "BI", name: "Burundi", dialCode: "+257", flag: "🇧🇮", phoneLength: 8 },
    { code: "KH", name: "Cambodge", dialCode: "+855", flag: "🇰🇭", phoneLength: 9 },
    { code: "CM", name: "Cameroun", dialCode: "+237", flag: "🇨🇲", phoneLength: 9 },
    { code: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦", phoneLength: 10 },
    { code: "CV", name: "Cap-Vert", dialCode: "+238", flag: "🇨🇻", phoneLength: 7 },
    { code: "CF", name: "Centrafrique", dialCode: "+236", flag: "🇨🇫", phoneLength: 8 },
    { code: "CL", name: "Chili", dialCode: "+56", flag: "🇨🇱", phoneLength: 9 },
    { code: "CN", name: "Chine", dialCode: "+86", flag: "🇨🇳", phoneLength: 11 },
    { code: "CY", name: "Chypre", dialCode: "+357", flag: "🇨🇾", phoneLength: 8 },
    { code: "CO", name: "Colombie", dialCode: "+57", flag: "🇨🇴", phoneLength: 10 },
    { code: "KM", name: "Comores", dialCode: "+269", flag: "🇰🇲", phoneLength: 7 },
    { code: "CG", name: "Congo", dialCode: "+242", flag: "🇨🇬", phoneLength: 9 },
    { code: "KP", name: "Corée du Nord", dialCode: "+850", flag: "🇰🇵", phoneLength: 10 },
    { code: "KR", name: "Corée du Sud", dialCode: "+82", flag: "🇰🇷", phoneLength: 10 },
    { code: "CR", name: "Costa Rica", dialCode: "+506", flag: "🇨🇷", phoneLength: 8 },
    { code: "CI", name: "Côte d'Ivoire", dialCode: "+225", flag: "🇨🇮", phoneLength: 10 },
    { code: "HR", name: "Croatie", dialCode: "+385", flag: "🇭🇷", phoneLength: 9 },
    { code: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺", phoneLength: 8 },
    { code: "DK", name: "Danemark", dialCode: "+45", flag: "🇩🇰", phoneLength: 8 },
    { code: "DJ", name: "Djibouti", dialCode: "+253", flag: "🇩🇯", phoneLength: 8 },
    { code: "DM", name: "Dominique", dialCode: "+1767", flag: "🇩🇲", phoneLength: 10 },
    { code: "EG", name: "Égypte", dialCode: "+20", flag: "🇪🇬", phoneLength: 10 },
    { code: "AE", name: "Émirats arabes unis", dialCode: "+971", flag: "🇦🇪", phoneLength: 9 },
    { code: "EC", name: "Équateur", dialCode: "+593", flag: "🇪🇨", phoneLength: 9 },
    { code: "ER", name: "Érythrée", dialCode: "+291", flag: "🇪🇷", phoneLength: 7 },
    { code: "ES", name: "Espagne", dialCode: "+34", flag: "🇪🇸", phoneLength: 9 },
    { code: "EE", name: "Estonie", dialCode: "+372", flag: "🇪🇪", phoneLength: 8 },
    { code: "SZ", name: "Eswatini", dialCode: "+268", flag: "🇸🇿", phoneLength: 8 },
    { code: "US", name: "États-Unis", dialCode: "+1", flag: "🇺🇸", phoneLength: 10 },
    { code: "ET", name: "Éthiopie", dialCode: "+251", flag: "🇪🇹", phoneLength: 9 },
    { code: "FJ", name: "Fidji", dialCode: "+679", flag: "🇫🇯", phoneLength: 7 },
    { code: "FI", name: "Finlande", dialCode: "+358", flag: "🇫🇮", phoneLength: 10 },
    { code: "FR", name: "France", dialCode: "+33", flag: "🇫🇷", phoneLength: 9 },
    { code: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦", phoneLength: 7 },
    { code: "GM", name: "Gambie", dialCode: "+220", flag: "🇬🇲", phoneLength: 7 },
    { code: "GE", name: "Géorgie", dialCode: "+995", flag: "🇬🇪", phoneLength: 9 },
    { code: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭", phoneLength: 9 },
    { code: "GI", name: "Gibraltar", dialCode: "+350", flag: "🇬🇮", phoneLength: 8 },
    { code: "GR", name: "Grèce", dialCode: "+30", flag: "🇬🇷", phoneLength: 10 },
    { code: "GD", name: "Grenade", dialCode: "+1473", flag: "🇬🇩", phoneLength: 10 },
    { code: "GL", name: "Groenland", dialCode: "+299", flag: "🇬🇱", phoneLength: 6 },
    { code: "GP", name: "Guadeloupe", dialCode: "+590", flag: "🇬🇵", phoneLength: 9 },
    { code: "GU", name: "Guam", dialCode: "+1671", flag: "🇬🇺", phoneLength: 10 },
    { code: "GT", name: "Guatemala", dialCode: "+502", flag: "🇬🇹", phoneLength: 8 },
    { code: "GG", name: "Guernesey", dialCode: "+44", flag: "🇬🇬", phoneLength: 10 },
    { code: "GN", name: "Guinée", dialCode: "+224", flag: "🇬🇳", phoneLength: 9 },
    { code: "GQ", name: "Guinée équatoriale", dialCode: "+240", flag: "🇬🇶", phoneLength: 9 },
    { code: "GW", name: "Guinée-Bissau", dialCode: "+245", flag: "🇬🇼", phoneLength: 7 },
    { code: "GY", name: "Guyana", dialCode: "+592", flag: "🇬🇾", phoneLength: 7 },
    { code: "GF", name: "Guyane française", dialCode: "+594", flag: "🇬🇫", phoneLength: 9 },
    { code: "HT", name: "Haïti", dialCode: "+509", flag: "🇭🇹", phoneLength: 8 },
    { code: "HN", name: "Honduras", dialCode: "+504", flag: "🇭🇳", phoneLength: 8 },
    { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰", phoneLength: 8 },
    { code: "HU", name: "Hongrie", dialCode: "+36", flag: "🇭🇺", phoneLength: 9 },
    { code: "IN", name: "Inde", dialCode: "+91", flag: "🇮🇳", phoneLength: 10 },
    { code: "ID", name: "Indonésie", dialCode: "+62", flag: "🇮🇩", phoneLength: 11 },
    { code: "IQ", name: "Irak", dialCode: "+964", flag: "🇮🇶", phoneLength: 10 },
    { code: "IR", name: "Iran", dialCode: "+98", flag: "🇮🇷", phoneLength: 10 },
    { code: "IE", name: "Irlande", dialCode: "+353", flag: "🇮🇪", phoneLength: 9 },
    { code: "IS", name: "Islande", dialCode: "+354", flag: "🇮🇸", phoneLength: 7 },
    { code: "IL", name: "Israël", dialCode: "+972", flag: "🇮🇱", phoneLength: 9 },
    { code: "IT", name: "Italie", dialCode: "+39", flag: "🇮🇹", phoneLength: 10 },
    { code: "JM", name: "Jamaïque", dialCode: "+1876", flag: "🇯🇲", phoneLength: 10 },
    { code: "JP", name: "Japon", dialCode: "+81", flag: "🇯🇵", phoneLength: 10 },
    { code: "JE", name: "Jersey", dialCode: "+44", flag: "🇯🇪", phoneLength: 10 },
    { code: "JO", name: "Jordanie", dialCode: "+962", flag: "🇯🇴", phoneLength: 9 },
    { code: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿", phoneLength: 10 },
    { code: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪", phoneLength: 10 },
    { code: "KG", name: "Kirghizistan", dialCode: "+996", flag: "🇰🇬", phoneLength: 9 },
    { code: "KI", name: "Kiribati", dialCode: "+686", flag: "🇰🇮", phoneLength: 8 },
    { code: "KW", name: "Koweït", dialCode: "+965", flag: "🇰🇼", phoneLength: 8 },
    { code: "LA", name: "Laos", dialCode: "+856", flag: "🇱🇦", phoneLength: 9 },
    { code: "LS", name: "Lesotho", dialCode: "+266", flag: "🇱🇸", phoneLength: 8 },
    { code: "LV", name: "Lettonie", dialCode: "+371", flag: "🇱🇻", phoneLength: 8 },
    { code: "LB", name: "Liban", dialCode: "+961", flag: "🇱🇧", phoneLength: 8 },
    { code: "LR", name: "Liberia", dialCode: "+231", flag: "🇱🇷", phoneLength: 8 },
    { code: "LY", name: "Libye", dialCode: "+218", flag: "🇱🇾", phoneLength: 10 },
    { code: "LI", name: "Liechtenstein", dialCode: "+423", flag: "🇱🇮", phoneLength: 7 },
    { code: "LT", name: "Lituanie", dialCode: "+370", flag: "🇱🇹", phoneLength: 8 },
    { code: "LU", name: "Luxembourg", dialCode: "+352", flag: "🇱🇺", phoneLength: 9 },
    { code: "MO", name: "Macao", dialCode: "+853", flag: "🇲🇴", phoneLength: 8 },
    { code: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬", phoneLength: 9 },
    { code: "MY", name: "Malaisie", dialCode: "+60", flag: "🇲🇾", phoneLength: 10 },
    { code: "MW", name: "Malawi", dialCode: "+265", flag: "🇲🇼", phoneLength: 9 },
    { code: "MV", name: "Maldives", dialCode: "+960", flag: "🇲🇻", phoneLength: 7 },
    { code: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱", phoneLength: 8 },
    { code: "MT", name: "Malte", dialCode: "+356", flag: "🇲🇹", phoneLength: 8 },
    { code: "MA", name: "Maroc", dialCode: "+212", flag: "🇲🇦", phoneLength: 9 },
    { code: "MQ", name: "Martinique", dialCode: "+596", flag: "🇲🇶", phoneLength: 9 },
    { code: "MU", name: "Maurice", dialCode: "+230", flag: "🇲🇺", phoneLength: 8 },
    { code: "MR", name: "Mauritanie", dialCode: "+222", flag: "🇲🇷", phoneLength: 8 },
    { code: "YT", name: "Mayotte", dialCode: "+262", flag: "🇾🇹", phoneLength: 9 },
    { code: "MX", name: "Mexique", dialCode: "+52", flag: "🇲🇽", phoneLength: 10 },
    { code: "MD", name: "Moldavie", dialCode: "+373", flag: "🇲🇩", phoneLength: 8 },
    { code: "MC", name: "Monaco", dialCode: "+377", flag: "🇲🇨", phoneLength: 8 },
    { code: "MN", name: "Mongolie", dialCode: "+976", flag: "🇲🇳", phoneLength: 8 },
    { code: "ME", name: "Monténégro", dialCode: "+382", flag: "🇲🇪", phoneLength: 8 },
    { code: "MS", name: "Montserrat", dialCode: "+1664", flag: "🇲🇸", phoneLength: 10 },
    { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿", phoneLength: 9 },
    { code: "MM", name: "Myanmar", dialCode: "+95", flag: "🇲🇲", phoneLength: 9 },
    { code: "NA", name: "Namibie", dialCode: "+264", flag: "🇳🇦", phoneLength: 9 },
    { code: "NR", name: "Nauru", dialCode: "+674", flag: "🇳🇷", phoneLength: 7 },
    { code: "NP", name: "Népal", dialCode: "+977", flag: "🇳🇵", phoneLength: 10 },
    { code: "NI", name: "Nicaragua", dialCode: "+505", flag: "🇳🇮", phoneLength: 8 },
    { code: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪", phoneLength: 8 },
    { code: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬", phoneLength: 10 },
    { code: "NU", name: "Niue", dialCode: "+683", flag: "🇳🇺", phoneLength: 4 },
    { code: "NO", name: "Norvège", dialCode: "+47", flag: "🇳🇴", phoneLength: 8 },
    { code: "NC", name: "Nouvelle-Calédonie", dialCode: "+687", flag: "🇳🇨", phoneLength: 6 },
    { code: "NZ", name: "Nouvelle-Zélande", dialCode: "+64", flag: "🇳🇿", phoneLength: 9 },
    { code: "OM", name: "Oman", dialCode: "+968", flag: "🇴🇲", phoneLength: 8 },
    { code: "UG", name: "Ouganda", dialCode: "+256", flag: "🇺🇬", phoneLength: 9 },
    { code: "UZ", name: "Ouzbékistan", dialCode: "+998", flag: "🇺🇿", phoneLength: 9 },
    { code: "PK", name: "Pakistan", dialCode: "+92", flag: "🇵🇰", phoneLength: 10 },
    { code: "PW", name: "Palaos", dialCode: "+680", flag: "🇵🇼", phoneLength: 7 },
    { code: "PA", name: "Panama", dialCode: "+507", flag: "🇵🇦", phoneLength: 8 },
    { code: "PG", name: "Papouasie-Nouvelle-Guinée", dialCode: "+675", flag: "🇵🇬", phoneLength: 8 },
    { code: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾", phoneLength: 9 },
    { code: "NL", name: "Pays-Bas", dialCode: "+31", flag: "🇳🇱", phoneLength: 9 },
    { code: "PE", name: "Pérou", dialCode: "+51", flag: "🇵🇪", phoneLength: 9 },
    { code: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇭", phoneLength: 10 },
    { code: "PL", name: "Pologne", dialCode: "+48", flag: "🇵🇱", phoneLength: 9 },
    { code: "PF", name: "Polynésie française", dialCode: "+689", flag: "🇵🇫", phoneLength: 6 },
    { code: "PR", name: "Porto Rico", dialCode: "+1", flag: "🇵🇷", phoneLength: 10 },
    { code: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹", phoneLength: 9 },
    { code: "QA", name: "Qatar", dialCode: "+974", flag: "🇶🇦", phoneLength: 8 },
    { code: "CD", name: "RD Congo", dialCode: "+243", flag: "🇨🇩", phoneLength: 9 },
    { code: "DO", name: "République dominicaine", dialCode: "+1", flag: "🇩🇴", phoneLength: 10 },
    { code: "CZ", name: "République tchèque", dialCode: "+420", flag: "🇨🇿", phoneLength: 9 },
    { code: "RE", name: "Réunion", dialCode: "+262", flag: "🇷🇪", phoneLength: 9 },
    { code: "RO", name: "Roumanie", dialCode: "+40", flag: "🇷🇴", phoneLength: 9 },
    { code: "GB", name: "Royaume-Uni", dialCode: "+44", flag: "🇬🇧", phoneLength: 10 },
    { code: "RU", name: "Russie", dialCode: "+7", flag: "🇷🇺", phoneLength: 10 },
    { code: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼", phoneLength: 9 },
    { code: "KN", name: "Saint-Christophe-et-Niévès", dialCode: "+1869", flag: "🇰🇳", phoneLength: 10 },
    { code: "SM", name: "Saint-Marin", dialCode: "+378", flag: "🇸🇲", phoneLength: 10 },
    { code: "VC", name: "Saint-Vincent-et-les-Grenadines", dialCode: "+1784", flag: "🇻🇨", phoneLength: 10 },
    { code: "LC", name: "Sainte-Lucie", dialCode: "+1758", flag: "🇱🇨", phoneLength: 10 },
    { code: "SV", name: "Salvador", dialCode: "+503", flag: "🇸🇻", phoneLength: 8 },
    { code: "WS", name: "Samoa", dialCode: "+685", flag: "🇼🇸", phoneLength: 7 },
    { code: "ST", name: "Sao Tomé-et-Principe", dialCode: "+239", flag: "🇸🇹", phoneLength: 7 },
    { code: "SN", name: "Sénégal", dialCode: "+221", flag: "🇸🇳", phoneLength: 9 },
    { code: "RS", name: "Serbie", dialCode: "+381", flag: "🇷🇸", phoneLength: 9 },
    { code: "SC", name: "Seychelles", dialCode: "+248", flag: "🇸🇨", phoneLength: 7 },
    { code: "SL", name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱", phoneLength: 8 },
    { code: "SG", name: "Singapour", dialCode: "+65", flag: "🇸🇬", phoneLength: 8 },
    { code: "SK", name: "Slovaquie", dialCode: "+421", flag: "🇸🇰", phoneLength: 9 },
    { code: "SI", name: "Slovénie", dialCode: "+386", flag: "🇸🇮", phoneLength: 8 },
    { code: "SO", name: "Somalie", dialCode: "+252", flag: "🇸🇴", phoneLength: 8 },
    { code: "SD", name: "Soudan", dialCode: "+249", flag: "🇸🇩", phoneLength: 9 },
    { code: "SS", name: "Soudan du Sud", dialCode: "+211", flag: "🇸🇸", phoneLength: 9 },
    { code: "LK", name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰", phoneLength: 9 },
    { code: "SE", name: "Suède", dialCode: "+46", flag: "🇸🇪", phoneLength: 9 },
    { code: "CH", name: "Suisse", dialCode: "+41", flag: "🇨🇭", phoneLength: 9 },
    { code: "SR", name: "Suriname", dialCode: "+597", flag: "🇸🇷", phoneLength: 7 },
    { code: "SY", name: "Syrie", dialCode: "+963", flag: "🇸🇾", phoneLength: 9 },
    { code: "TJ", name: "Tadjikistan", dialCode: "+992", flag: "🇹🇯", phoneLength: 9 },
    { code: "TW", name: "Taïwan", dialCode: "+886", flag: "🇹🇼", phoneLength: 9 },
    { code: "TZ", name: "Tanzanie", dialCode: "+255", flag: "🇹🇿", phoneLength: 9 },
    { code: "TD", name: "Tchad", dialCode: "+235", flag: "🇹🇩", phoneLength: 8 },
    { code: "TH", name: "Thaïlande", dialCode: "+66", flag: "🇹🇭", phoneLength: 9 },
    { code: "TL", name: "Timor oriental", dialCode: "+670", flag: "🇹🇱", phoneLength: 8 },
    { code: "TG", name: "Togo", dialCode: "+228", flag: "🇹🇬", phoneLength: 8 },
    { code: "TO", name: "Tonga", dialCode: "+676", flag: "🇹🇴", phoneLength: 7 },
    { code: "TT", name: "Trinité-et-Tobago", dialCode: "+1868", flag: "🇹🇹", phoneLength: 10 },
    { code: "TN", name: "Tunisie", dialCode: "+216", flag: "🇹🇳", phoneLength: 8 },
    { code: "TM", name: "Turkménistan", dialCode: "+993", flag: "🇹🇲", phoneLength: 8 },
    { code: "TR", name: "Turquie", dialCode: "+90", flag: "🇹🇷", phoneLength: 10 },
    { code: "TV", name: "Tuvalu", dialCode: "+688", flag: "🇹🇻", phoneLength: 6 },
    { code: "UA", name: "Ukraine", dialCode: "+380", flag: "🇺🇦", phoneLength: 9 },
    { code: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾", phoneLength: 8 },
    { code: "VU", name: "Vanuatu", dialCode: "+678", flag: "🇻🇺", phoneLength: 7 },
    { code: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪", phoneLength: 10 },
    { code: "VN", name: "Vietnam", dialCode: "+84", flag: "🇻🇳", phoneLength: 10 },
    { code: "YE", name: "Yémen", dialCode: "+967", flag: "🇾🇪", phoneLength: 9 },
    { code: "ZM", name: "Zambie", dialCode: "+260", flag: "🇿🇲", phoneLength: 9 },
    { code: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼", phoneLength: 9 },
];

export const getCountryByCode = (code: string): Country | undefined => {
    return countries.find(country => country.code === code);
};

export const getCountryByDialCode = (dialCode: string): Country | undefined => {
    return countries.find(country => country.dialCode === dialCode);
};

export const getCountryByName = (name: string): Country | undefined => {
    return countries.find(country => country.name.toLowerCase() === name.toLowerCase());
};
